### ISSUE TITLE
DG412 version substitution

### ISSUE THREAD

**Issue by extremenerble** [drChungus/VCSequentialSwitch#10]
Hello, it seems there's a [<$2 version](https://www.mouser.com/ProductDetail/Vishay-Semiconductors/DG412DQ-T1-E3?qs=avFSO%252B7Rp3jHOzwqyNEU6w%3D%3D) of the DG412 compared to the [$7 version](https://www.mouser.com/ProductDetail/Analog-Devices/ADG5412BRUZ-REEL7?qs=BpaRKvA4VqEmn7QB78QemQ%3D%3D) listed in the Eagle BOM. Is there any harm in using the cheaper one?

The only real differences are a lower minimum supply voltage and these:

Spec | cheaper part  | original part
Off Time - Max: | 160 ns | 145 ns
On Resistance - Max: | 45 Ohms | 11 Ohms
On Time - Max: | 240 ns | 202 ns

Thanks in advance.

**Comment by drChungus** [comment]
Hey there!
By looking at the Datasheet I believe the substitution would work. As you noted, the biggest difference is the increased resistance. This would not make a noticeable difference when routing triggers/gates or audio signals, bit the increased voltage drop would affect control voltage, making V/Oct signals be more out of tune. In general I would recommend quantizing such signal routed through the switch anyway, but the replacement part would make this imperfection more pronounced.
Note that no testing was or could be performed by myself with the replacement part you mentioned, but I would be thrilled to hear back from you if you go ahead and build the unit with the cheaper part.

**Comment by extremenerble** [comment]
thanks for the feedback! i may try one with the cheaper chips and one with the correct chips. i think having v/Oct may be key for a lot of patches. 

cheers
