### ISSUE TITLE
Incorrect BOM?

### ISSUE THREAD

**Issue by KeLaiFu** [drChungus/VCSequentialSwitch#6]
I just had these boards made up and grabbed the BOM from various stores while I was waiting for delivery. However the IC listed for IC1 and 2, accoridng to the BOM is a DG5412, which is a different chip to the one thats expected on the board. I made a new BOM from the eagle file and it lists a DG412DJC1 for that reference, which looks like the correct china according to the footprint.

**Comment by drChungus** [comment]
Hey @KeLaiFu ,

You are correct, I recon replacing the DG412 with a more modern alternative, but the actual prototypes I made use the DG412. Regarding functionality, the DG5412 is a direct replacement of the DG412, but does not seem to be available in an SOIC package, which is used on the final PCB. Thus the BOM should refer to the DG412, also to be consistent with he EAGLE file.

Thanks for the heads-up!
