### ISSUE TITLE
Still large differences between published BOM and eagle created BOM

### ISSUE THREAD

**Issue by KeLaiFu** [drChungus/VCSequentialSwitch#7]
As per title, the BOM created from eagle is very different to the BOM published in the repo. Can you clarify if I should just follow the BOM from Eagle, I would assume this one to be correct but I am not experienced in eagle to be sure.

**Comment by drChungus** [comment]
Hey, 
the most recent design is made in EAGLE and the only BOMs generated are for the archived (aka deprecated) version. Feel free to generate the BOM from EAGLE. 
The parts needed are the passives, the 4017, the DG412 and the 3904s. Use the parts listed in the EAGLE file and make sure you pick the ones with the proper footprint.
