### ISSUE TITLE
Brighter LEDs?

### ISSUE THREAD

**Issue by KeLaiFu** [drChungus/VCSequentialSwitch#8]
Ok so this should be my last 'issue'!

I've successfully built the module and it works great, so thanks for sharing this great project, buuuut, is there a way to increase the brightness the LEDs? Currently my lights are easily visible, but they would certainly benefit to being a lot brighter. I looked around the PCB and the voltage for the LEDS seems to be coming directly from a chip leg, although I could well be mistaken.

**Comment by drChungus** [comment]
Hey there @KeLaiFu!

You can adjust the brightness of the LEDs by switching the value of R1 on the IO board. If you want to have your lights brighter, simply replace the resistor to a lower value, and vice-versa. I recommend you have a look at the datasheet of the LEDs you use, so you can have a reference on what current you want to drive them with. 
Note that R1 is the only resistor on the IO PCB. As practically only one LED is expected to be on at any given time, the current limiting resistor is a common one for all the stages.
Fun fact: I built the modules with warm white LEDs, hence the higher resistance for the current limiting.
